### PR TITLE
Initial Jira99 Instructions

### PR DESCRIPTION
**Pull request by rhkp**
Hi @mpaulgreen 
Please review the pull request for the basic topology and accept or advise of changes, if any. 
Thanks.
@rhkp

### CODE REVIEW

**Comment by mpaulgreen** [comment]
@rhkp , I just had a glance at it. In IBM Cloud Core Component Inventory, you mentioned that you have used 3 gateways, one to connect two regions and one to connect the two VMs in different availability zones.  You should be able to connect to VMs of 2 availability zones by opening the ports of security groups associated.  We should not need transit gateways for connecting 2 Vms in different availability zones. Can you please make the necessary changes?

**Comment by mpaulgreen** [comment]
@rhkp - Can you include the configuration details for the following statement - 
Ms in two Availability Zones (e.g. TOR1 and TOR2) can connect to each other with suitable changes to security groups
For two VMs to connect, which belong in two separate VPCs (e.g WDC VPC and TOR VPC) in two separate Regions (e.g. TOR and WDC), one needs to use Global Transit Gateway in IBM Cloud. ***This will be based on your current port configurations***

Also, region1 master and slave should mirror to region2 master and slave and vice versa. We ***WILL*** loose messages if HA is initiated in region1 and then after some time there is a disaster in region1.

**Comment by rhkp** [comment]
@mpaulgreen Okay sure. Let me see if I can add more/further mirroring config and how it works.

**Comment by mpaulgreen** [comment]
@rhkp I just glanced you SGs, narrow down your SG rules to specific port and IP address except for port that provides the web access that will be accessible for time being to ANY. Generally in production system, network admin will not allow it to be deployed with such wide range rules.

**Comment by rhkp** [comment]
@mpaulgreen Please check and advise about this config. Thanks.

**Pull request merged**
