### PR TITLE
Initial code for Cluster running in HA - replication mode

### PR DESCRIPTION
**Pull request by sgahlot**

### CODE REVIEW

**Review by mpaulgreen — COMMENTED** [review]
@sgahlot, please include the current firewall rules on your VM in the readme.md.

**Comment by sgahlot** [comment]
There are no firewall rules so far. It's running with default rules.

**Comment by mpaulgreen** [comment]
@sgahlot Add the instruction to install opnejdk.  Change the instruction heading from "HA replication QuickStart"

**Comment by sgahlot** [comment]
@mpaulgreen what do you want the heading to be? I think your comment is not finished.

I'll add the section for installing openjdk 11.

**Pull request merged**
